name: Docker Build Push
on:
  pull_request:
  workflow_dispatch:
  push:
jobs:
  Build-Scan-Container:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd-local.yaml@main
    with:
      dockerfile: Dockerfile
